version: "3.8"
services:
  frontend:
    image: node:18-alpine
    volumes:
      - ./frontend:/frontend
      - ./.config:/.config
    working_dir: /frontend
    command: sh -c "npm run dev -- --host 0.0.0.0"
    ports:
      - "8080:5173"
    depends_on:
      - server

  server:
    image: node:18-alpine
    volumes:
      - ./server:/server
      - ./.config:/.config
    working_dir: /server
    command: sh -c "npm run dev"
    ports:
      - "3000:3000"
